### ISSUE TITLE
Use crc_ccitt_ffff for calculate from hexa data

### ISSUE THREAD

**Issue by DBeloglazov** [lammertb/libcrc#11]
Hello. 
How i can use crc_ccitt_ffff(*,*) for calculation crc from hexa data? My data for crc is 890249780003A0015370C70119004FFB700039FC9FFFF4FE1EFFFFFFDDFFED00000526402A5A193DF87D50. 
I need crc value 0xA9B6, but i have 0x1E66 (data calculated as ASCII). How i can fix it?

**Comment by lammertb** [comment]
You can fix it by reading the documentation of the device or software where this data and CRC is used. Often there are additional byte swaps, or bit inversions taking place to get the wanted result.

As the problem raised here is not an issue of the library itself, I will close it now.
