### ISSUE TITLE
Does not build on Ubuntu 18.04 64-bit

### ISSUE THREAD

**Issue by RolandHughes** [lammertb/libcrc#12]
I pulled down the zip file today and tried to build on Ubuntu 18.04 64-bit with all updates applied.
![libcrc-build-error](https://user-images.githubusercontent.com/1883220/59979826-6869eb00-95b2-11e9-94dd-c24859fa166d.PNG)

I assume this is because the compiler standards are a wee bit tighter now.

**Comment by lammertb** [comment]
I managed to create a testing environment with Ubuntu 18.04 64 bit and report the results back here.

**Comment by lammertb** [comment]
Fixed in a recent commit
