### ISSUE TITLE
Xmodem CRC result does not match "official" document

### ISSUE THREAD

**Issue by RhinoDevel** [lammertb/libcrc#13]
At least on [your website](https://www.lammertbies.nl/comm/info/crc-calculation.html) I cannot find the CRC-16 result matching the result calculated by Xmodem CRC function found in "official" XMODEM/YMODEM documentation file from [http://pauillac.inria.fr/~doligez/zmodem/ymodem.txt](http://pauillac.inria.fr/~doligez/zmodem/ymodem.txt), page 25.

E.g. result for ASCII 123456789  is 0xBEEF.

**Comment by lammertb** [comment]
I am not sure where you found the 0xBEEF check result. I couldn't find it in the document you referenced. As far as I know the check result should be 0x31C3, as for example mentioned in [this list](http://crcmod.sourceforge.net/crcmod.predefined.html) of CRC check results.

**Comment by RhinoDevel** [comment]
I calculated the result 0xBEEF with the function mentioned and another (table-based) implementation I found. But either these implementations are no longer used, or I made a logical error on the way, because now I could reproduce the checksum calculated by the "official"/default implementation ([https://ohse.de/uwe/software/lrzsz.html](https://ohse.de/uwe/software/lrzsz.html)) during an YMODEM transfer with your website. Sorry for the noise!!
