### ISSUE TITLE
Add <extern "C"> brackets to functions to make it usable in C++

### ISSUE THREAD

**Issue by ghost** [lammertb/libcrc#15]
To compile sources in C++ or mixing C/C++ projects, the <extern "C"> could surround function declarations in header-files, as well as implementations in source-files.

```
#ifdef __cplusplus
extern "C" {
#endif

{FUNCTION DEFINITIONS}

#ifdef __cplusplus
}
#endif
```

Background: https://www.oracle.com/technical-resources/articles/it-infrastructure/mixing-c-and-cplusplus.html (section "Creating Mixed-Language Headers")

**Comment by lammertb** [comment]
Thanks for the heads-up. I do not use C++ in production environments (most applications are embedded) but I will go through the documentation you mentioned to see how this can be implemented.

**Comment by lammertb** [comment]
Fixed
