### ISSUE TITLE
checksum.h - missing include

### ISSUE THREAD

**Issue by ratified1791** [lammertb/libcrc#5]
https://github.com/lammertb/libcrc/blob/master/include/checksum.h

needs the line:

#include <stddef.h>

...for the "size_t" parameters in the function calls.  I think it's included by default in a lot of cases, but I've got a stripped-down bootloader that threw an error without this inclusion.

**Comment by tepperly** [comment]
I see this too.

**Comment by greg4iiii** [comment]
+1

**Comment by lammertb** [comment]
Fixed in commit https://github.com/lammertb/libcrc/commit/fb02cee2b9dace391a8151e3e42b6802e4c2fa41
