### ISSUE TITLE
Embedded processors with small memory footprint

### ISSUE THREAD

**Issue by GMellar** [lammertb/libcrc#9]
I made some modifications for an embedded project where the memory footprint is critical but the calculation time of the crc is not. I modified the calculation function so that no lookup table is used or the lookup table is read from flash memory but this is very platform specific. Is there any interest to merge that into this project?

**Comment by lammertb** [comment]
There are many applications where different approaches to calculate CRC are necessary or preferred. This library is just one way for general purposes on many different platforms. Platform dependent solutions may mess up the code and prohibit easy future additions of additional algorithms. I would therefore propose that if you want to publish your code to create your own github repository to let future developers have the chance to use that code in their projects.
